#if UNITY_EDITOR
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

[CustomEditor(typeof(GDKSymbol))]
public class GDKSymbolEditor : Editor
{
    private const string GeneratedFolder = "Assets/_Project/_Asset/Scripts/Core/GDKSymbol/Generated";
    private const string GeneratedFileSuffix = ".GDKDebug.cs";

    public override void OnInspectorGUI()
    {
        DrawDefaultInspector();

        if (GUILayout.Button("Apply"))
            Apply((GDKSymbol)target);
    }

    private static void Apply(GDKSymbol symbol)
    {
        Directory.CreateDirectory(GeneratedFolder);

        var expectedFiles = new HashSet<string>();
        foreach (var (nameSpace, isActive) in symbol.Entries)
        {
            if (string.IsNullOrWhiteSpace(nameSpace)) continue;

            var fileName = SanitizeFileName(nameSpace) + GeneratedFileSuffix;
            expectedFiles.Add(fileName);
            File.WriteAllText(Path.Combine(GeneratedFolder, fileName), GenerateScript(nameSpace, isActive));
        }

        foreach (var existingFile in Directory.GetFiles(GeneratedFolder, "*" + GeneratedFileSuffix))
        {
            if (expectedFiles.Contains(Path.GetFileName(existingFile))) continue;

            File.Delete(existingFile);
            if (File.Exists(existingFile + ".meta"))
                File.Delete(existingFile + ".meta");
        }

        AssetDatabase.Refresh();
    }

    private static string SanitizeFileName(string nameSpace) => nameSpace.Replace(".", "_");

    private static readonly string[] WrappedMethods = { "Log", "LogWarning", "LogError" };

    private static string GenerateScript(string nameSpace, bool isActive)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by GDKSymbolEditor. Do not edit by hand.");
        sb.Append("namespace ").AppendLine(nameSpace);
        sb.AppendLine("{");
        sb.AppendLine("    public static class Debug");
        sb.AppendLine("    {");
        foreach (var method in WrappedMethods)
        {
            var body = isActive ? $"UnityEngine.Debug.{method}($\"[{nameSpace}] {{message}}\");" : string.Empty;
            sb.Append("        public static void ").Append(method).Append("(object message) { ").Append(body).AppendLine(" }");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
#endif
