#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using UnityEditor;
using UnityEditor.Build;
using UnityEngine;

namespace Core.GDKSymbol
{
    [CustomEditor(typeof(GDKSymbol))]
    public class GDKSymbolEditor : Editor
    {
        private const string GeneratedFolder = "Assets/_Project/_Asset/Scripts/Core/GDKSymbol/Generated";
        private const string GeneratedFileSuffix = ".GDKDebug.cs";

        private static readonly string[] WrappedMethods = { "Log", "LogWarning", "LogError" };

        public override void OnInspectorGUI()
        {
            DrawDefaultInspector();

            if (GUILayout.Button("Apply"))
                Apply((GDKSymbol)target);
        }

        private static void Apply(GDKSymbol symbol)
        {
            GenerateFiles(symbol);
            AssetDatabase.Refresh();
            SyncDefines(symbol);
        }

        private static void GenerateFiles(GDKSymbol symbol)
        {
            Directory.CreateDirectory(GeneratedFolder);

            var expectedFiles = new HashSet<string>();
            foreach (var (nameSpace, _) in symbol.Entries)
            {
                if (string.IsNullOrWhiteSpace(nameSpace)) continue;

                var fileName = Sanitize(nameSpace) + GeneratedFileSuffix;
                expectedFiles.Add(fileName);
                File.WriteAllText(Path.Combine(GeneratedFolder, fileName), GenerateScript(nameSpace));
            }

            foreach (var existingFile in Directory.GetFiles(GeneratedFolder, "*" + GeneratedFileSuffix))
            {
                if (expectedFiles.Contains(Path.GetFileName(existingFile))) continue;

                File.Delete(existingFile);
                if (File.Exists(existingFile + ".meta"))
                    File.Delete(existingFile + ".meta");
            }
        }

        // Entries drive the scripting define symbols: an enabled entry adds its define so the
        // matching [Conditional] logs compile in, a disabled/removed entry strips them from the build.
        private static void SyncDefines(GDKSymbol symbol)
        {
            var managed = new HashSet<string>();
            var enabled = new HashSet<string>();
            foreach (var (nameSpace, inBuild) in symbol.Entries)
            {
                if (string.IsNullOrWhiteSpace(nameSpace)) continue;

                var define = Sanitize(nameSpace);
                managed.Add(define);
                if (inBuild) enabled.Add(define);
            }

            foreach (var buildTarget in AllBuildTargets())
            {
                // Some NamedBuildTarget fields (e.g. deprecated platforms) are rejected by PlayerSettings.
                try
                {
                    var defines = PlayerSettings.GetScriptingDefineSymbols(buildTarget)
                        .Split(';', StringSplitOptions.RemoveEmptyEntries)
                        .Where(d => !managed.Contains(d))
                        .Concat(enabled)
                        .Distinct()
                        .ToArray();

                    PlayerSettings.SetScriptingDefineSymbols(buildTarget, defines);
                }
                catch (ArgumentException)
                {
                }
            }
        }

        private static IEnumerable<NamedBuildTarget> AllBuildTargets()
        {
            var seen = new HashSet<string>();
            foreach (var field in typeof(NamedBuildTarget).GetFields(BindingFlags.Public | BindingFlags.Static))
            {
                if (field.FieldType != typeof(NamedBuildTarget)) continue;

                var buildTarget = (NamedBuildTarget)field.GetValue(null);
                if (string.IsNullOrEmpty(buildTarget.TargetName) || buildTarget.TargetName == "Unknown") continue;

                if (seen.Add(buildTarget.TargetName))
                    yield return buildTarget;
            }
        }

        private static string Sanitize(string nameSpace) => nameSpace.Replace(".", "_");

        private static string GenerateScript(string nameSpace)
        {
            var define = Sanitize(nameSpace);
            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by GDKSymbolEditor. Do not edit by hand.");
            sb.Append("namespace GDKSymbol.").AppendLine(nameSpace);
            sb.AppendLine("{");
            sb.AppendLine("    public static class Debug");
            sb.AppendLine("    {");
            foreach (var method in WrappedMethods)
            {
                sb.Append("        [System.Diagnostics.Conditional(\"").Append(define).AppendLine("\")]");
                sb.Append("        public static void ").Append(method)
                    .Append("(object message) { UnityEngine.Debug.").Append(method)
                    .Append("($\"[").Append(nameSpace).Append("] {message}\"); }").AppendLine();
            }
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }
    }
#endif
}
